const request = require('./request');

async function main() {
  // GET
  try {
    const getResult = await request('GET', 'https://api.code.dev/objects');
    console.log('GET /objects:');
    console.log(getResult);
  } catch (err) {
    console.log('GET /objects failed:', err.message);
  }

  // POST
  let createdId = null;
  try {
    const postBody = {
      name: 'Apple MacBook Pro 16',
      data: {
        year: 2019,
        price: 1849.99,
        'CPU model': 'Intel Core i9',
        'Hard disk size': '1 TB',
      },
    };
    const postResult = await request('POST', 'https://api.code.dev/objects', postBody);
    console.log('POST /objects:');
    console.log(postResult);
    createdId = postResult.id; // grab the id generated by the server
  } catch (err) {
    console.log('POST /objects failed:', err.message);
  }

  // PUT - use the id returned from POST, not a hardcoded one
  if (createdId) {
    try {
      const putBody = {
        name: 'Apple MacBook Pro 16',
        data: {
          year: 2019,
          price: 2049.99,
          'CPU model': 'Intel Core i9',
          'Hard disk size': '1 TB',
          color: 'silver',
        },
      };
      const putResult = await request('PUT', `https://api.code.dev/objects/${createdId}`, putBody);
      console.log(`PUT /objects/${createdId}:`);
      console.log(putResult);
    } catch (err) {
      console.log(`PUT /objects/${createdId} failed:`, err.message);
    }
  } else {
    console.log('Skipping PUT — no id available from POST.');
  }
}

main();